name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, development, release ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      
      - name: Display commit info
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
      
      - name: Add platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux
      
      - name: Install dependencies
        run: bundle install
      
      - name: Run RSpec tests
        run: bundle exec rspec
      
      - name: Success message
        run: echo "All tests passed!"

  auto-approve:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
