name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, development, release ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      
      - name: Display commit info
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
      
      - name: Add platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux
      
      - name: Install dependencies
        run: bundle install
      
      - name: Run RSpec tests
        run: bundle exec rspec
      
      - name: Success message
        run: echo "All tests passed!"

  merge-to-main:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Merge development to main
        run: |
          git checkout main
          git merge --no-ff development -m "Auto merge development to main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
